version: '3.8'

networks:
  default:
    external:
      name:
        bapenda

services:
  minio:
    image: minio/minio:RELEASE.2022-12-12T19-27-27Z
    container_name: bapenda-minio-2
    ports:
      - "9090:9090"
      - "9091:9091"
    volumes:
      - "./data:/data"
    command: server /data --console-address ":9091" --address ":9090"
    environment:
      - MINIO_ROOT_USER=minio-root-user
      - MINIO_ROOT_PASSWORD=minio-root-password
    restart: unless-stopped