version: '3'

networks:
  default:
    external:
      name:
        bapenda

services:
  minio:
    image: 'bitnami/minio:latest'
    container_name: bapenda_minio
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      - MINIO_ROOT_USER=minio-root-user
      - MINIO_ROOT_PASSWORD=minio-root-password